### ISSUE TITLE
Remove “beta” / replace with “new”

### ISSUE THREAD

**Issue by andylolz** [CodeClub/lesson_format#128]
A volunteer at the London meetup mentioned it’s a bit weird that the printed PDFs say “beta” in the titles. I think I agree – this is definitely more of a volunteer-facing thing. We currently strip the “heads up!” text out of the PDFs, so maybe we should also strip the title prefix.

One simple way to do this (and tidy up a bit on the way) would be to add support for `beta: true` in the frontmatter of project markdown. When this flag is set, the “heads up!” and “beta” messages are automatically added to the html (but hidden from the PDF).

**Comment by CodeClubRik** [comment]
This is great, but from talking to our community manager is seems as though the mention of 'Beta' is putting volunteers off using new projects. How about if we:
+ Replace the text in the 'Heads up!" message to say 'new' instead of 'beta';
+ Remove the text '(Beta)' from the project title.

**Comment by andylolz** [comment]
Cool! Happy to sort this one.

**Comment by andylolz** [comment]
Modified issue according to [Rik’s comments](https://github.com/CodeClub/lesson_format/issues/128#issuecomment-71631464).

**Comment by CodeClubRik** [comment]
cheers @andylolz
