### ISSUE TITLE
Some files not appearing in the 'Download Project Materials' .zip

### ISSUE THREAD

**Issue by CodeClubRik** [CodeClub/lesson_format#130]
For example, in "Paint Box" (Scratch 1), the .md says:
`materials: ["PaintBox.sb2","PaintBoxResources.sb2","Resources/*.*"]`

but the file `PaintBoxResources.sb2` doesn't appear in the downloaded .zip (for me anyway).

This is also true for 'Boat Race' and 'Create Your Own World' Scratch projects.

**Comment by andylolz** [comment]
Is this fixed now?

**Comment by CodeClubRik** [comment]
Yep it seems that way. I'll close and reopen if needed! :)
