### ISSUE TITLE
Russian resources not displaying

### ISSUE THREAD

**Issue by CodeClubRik** [CodeClub/lesson_format#132]
Russian resources are showing locally but not on website?

![thumbnail 1](https://cloud.githubusercontent.com/assets/7372432/5917807/4db753f2-a619-11e4-86b6-dd17085059f1.png)

**Comment by andylolz** [comment]
In the past, this sort of problem has usually been due to a case sensitivity issue in a manifest.

(I haven’t checked, but that’s what I’d guess.)

Should really make it fail a bit more noisily. I think that’s what #54 is about, in fact.

**Comment by CodeClubRik** [comment]
I think you're right. I previously fixed the case-sensitivity and git didn't pick up the changes. I ran:

`git config --system core.ignorecase false`

**Comment by andylolz** [comment]
> and everything worked!

Nice one!

> I could add this to the repo's `.gitconfig` to stop this happening again?

I don’t think repos have a `.gitconfig` – it’s per instance :( It might be possible to do this in the `.gitattributes` file, though?? I don’t know.
