### ISSUE TITLE
Add feedback link to every project (not just beta ones)

### ISSUE THREAD

**Issue by CodeClubRik** [CodeClub/lesson_format#144]
as mentioned in #138 currently the project feedback link is a bubble at the top of beta projects.

it would be nice if this form was available somewhere for volunteers to give feedback on __any__ project.  this could be at the top of every project (as it currently is for beta projects) but maybe it could instead be in the term sections instead of individual projects?

oh, and there's a different form for Scratch / HTML / Python.

**Comment by CodeClubRik** [comment]
@andylolz suggested somewhere here maybe?

![top](https://cloud.githubusercontent.com/assets/7372432/6167494/d5b43d64-b2b3-11e4-98ee-9c8ddb6048c8.png)

**Comment by martinpeck** [comment]
More of a general question, rather than one specific to this issue: do we need to get a designer to spend some time on these generated web pages so that they have added awesome?

**Comment by CodeClubRik** [comment]
@martinpeck I think that would be great!

**Comment by andylolz** [comment]
Haha – let the record show that I most definitely flagged up my total lack of design skills!

> My design skills are non-existent. But there’s a lot of white space up here:
> http://cl.ly/image/1U2e2e0b3p1R
>
> Maybe we could use some of that? I dunno. Maybe another thing for
> someone with a design eye to take a look at, I guess!

**Comment by andylolz** [comment]
I've created a "design" label for issues that need a design eye.

**Comment by CodeClubRik** [comment]
FYI: here's the current [beta project feedback form](https://docs.google.com/forms/d/1eMCfpYe3v7eYu5M8rSqLKlmq7cczLCLHx66csgyUyVU/viewform?usp=send_form)

**Comment by CodeClubRik** [comment]
I'm closing this, because it's been done for codeclubprojects.org.
