### ISSUE TITLE
Legal information

### ISSUE THREAD

**Issue by codecleaner** [CodeClub/lesson_format#145]
On every page at projects.codeclubworld.org there is legal information:

![image](https://cloud.githubusercontent.com/assets/781153/6318237/1dafb0fa-ba87-11e4-929c-1964c6848c47.png)

I think it's a bug and this information applies rather to all projects from projects.codeclub.org.uk, am I right?

**Comment by andylolz** [comment]
You’re right – looks like a bug to me.

**Comment by andylolz** [comment]
Looks like there was a copy/paste error in 1f45bde4.

**Comment by andylolz** [comment]
Fixed in e723a1ea. Note that the fix won’t take effect until @codeclubrobot next runs.

**Comment by codecleaner** [comment]
OK. Thanks for fixing it @andylolz!

**Comment by andylolz** [comment]
@codeclubrik CodeClub/CodeClubWorld-Projects#39 fixes this

**Comment by CodeClubRik** [comment]
@andylolz merged! :)

**Comment by andylolz** [comment]
Nice! Thanks, Rik!

(I would totally close this issue now, but I already closed it. Sad face.)
