### ISSUE TITLE
output force-added to this repo

### ISSUE THREAD

**Issue by andylolz** [CodeClub/lesson_format#149]
This repo currently contains the [built UK output](https://github.com/CodeClub/lesson_format/tree/master/output/codeclubuk/en-GB/07_scratch_bonus).

I’m assuming `git add --force output` was run by accident? @CodeClubRik do you mind if I remove this and then do a `git push --force`?

**Comment by CodeClubRik** [comment]
Yep, that's no problem!

**Comment by andylolz** [comment]
Great – fixed now.
