### ISSUE TITLE
Remove AMENDING.md as it doesn't make sense

### ISSUE THREAD

**Issue by martinpeck** [CodeClub/lesson_format#152]
This file doesn't appear to make sense for this repository, and refers to files that don't exist. Probably better to nuke it until we're sure what it should say.

**Comment by andylolz** [comment]
Yeah – AMENDING.md shouldn’t be here… Instead there should be the equivalent of [CONTRIBUTING.md on the curriculum repos](https://github.com/CodeClub/scratch-curriculum/blob/d3fde5d6/CONTRIBUTING.md).

The idea is these files all funnel contributors into [the documentation repo](https://github.com/CodeClub/curriculum_documentation).

**Comment by andylolz** [comment]
Added in 66d556e8
