### ISSUE TITLE
Remove UK specific code paths from build.py

### ISSUE THREAD

**Issue by martinpeck** [CodeClub/lesson_format#155]
There are two places where the logic branches based upon the build being performed for UK vs CCW. No one appears to know why, and it causes inconsistencies that are unexpected, so remove them.

Let's be one big happy family.

**Comment by andylolz** [comment]
The relevant commit appears to be e26b06e2.

Presumably this comes from the days of manually generated UK-theme PDFs in the curriculum repos, and no CCW PDFs. In that case, it wouldn’t be desirable to copy UK-theme PDFs to CCW project site(s).

I’m _fairly_ sure it’s now defunct.

**Comment by martinpeck** [comment]
Did this is in SHA: c170233cb7d8f6f5ddf3c6a94e8f45427caf5731 but forgot to connect the dots.
