### ISSUE TITLE
Link to CC Terms of Service on http://projects.codeclub.org.uk/

### ISSUE THREAD

**Issue by SarahSC** [CodeClub/lesson_format#157]
People who use our projects are technically bound by our Terms of Service. 

Please can we add a link somewhere on the http://projects.codeclub.org.uk/ landing page?

**Comment by arve0** [comment]
Adding, which license the lessons are under could be more clear. It's stated somewhere ([like here](https://www.codeclub.org.uk/faqs) under *Who can use our projects?*) that the *work* is creative commons by-nc-sa 4.0.

**Comment by andylolz** [comment]
For reference, [here are the Terms of Service](https://s3.amazonaws.com/codeclub-assets/public/Code+Club+Terms+of+Service+v10.pdf).

> People who use our projects are technically bound by our Terms of Service

Hmm… Is this compatible with the license?

**Comment by Jonic** [comment]
What do you mean Andy? Can you elaborate please?

**Comment by martinpeck** [comment]
Let's take this offline. Licensing and terms of service discussions are
underway elsewhere.

On Friday, 10 April 2015, Jonic Linley <notifications@github.com> wrote:

> What do you mean Andy? Can you elaborate please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CodeClub/lesson_format/issues/157#issuecomment-91543487>
> .
>


-- 
Cheers, Martin

**Comment by arve0** [comment]
I think what he means is (at least what Kodeklubben in Norway is wondering about): If the lessons are licensed under cc-by-nc-sa 4.0, could one at the same time be bound by the terms of service? Terms of service might be incompatible with the cc license, and double licensing would not make sense.

**Comment by andylolz** [comment]
Thanks @arve0 – exactly.

**Comment by martinpeck** [comment]
Addressed in SHA: 14652faa6c98323478f89d95c6a62f26092f68df
