### ISSUE TITLE
Terms of service errors

### ISSUE THREAD

**Issue by andylolz** [CodeClub/lesson_format#160]
The references in the [Terms of Service doc](https://www.codeclub.org.uk/terms-and-conditions) (linked in the footer) seem muddled. Presumably it has been rejigged, but the inline references haven’t been updated. For instance, 2.2 references itself:

> 2.2(e). immediately inform us and the educational institution at which you perform the sessions of
the occurrence of any matter set out in __paragraph 2.2__ below. 

So does 2.5:

> 2.5. You acknowledge and agree that working with children is a regulated activity in the UK. You
understand that if we become aware of any breach of any of the undertakings in __clause 2.5__ […]

There are also a couple of instances of placeholders that say “[URL]” instead of the actual URL (in 2.6(e) and 3.4).

**Comment by martinpeck** [comment]
Thanks. I'm going to migrate this bug to the private repository for the CCUK site as this is where those terms are defined and hosted.

**Comment by andylolz** [comment]
Cool, sounds good.

It’s a shame github doesn’t allow you to have a public issue tracker on a private repo. They suggest this somewhat unsatisfactory solution:
https://help.github.com/articles/issues-only-access-permissions/

**Comment by andylolz** [comment]
It looks like this document has now been revised and these bugs fixed.
