### ISSUE TITLE
Padding between activity steps

### ISSUE THREAD

**Issue by rikcross** [CodeClub/lesson_format#163]
There's no padding after a step that ends with a list. For example:

![screen shot 2015-05-27 at 20 03 30](https://cloud.githubusercontent.com/assets/7372432/7844971/cdda6efc-04ab-11e5-8d89-ffce7fcc6865.png)

**Comment by CodeClubRik** [comment]
This isn't at all urgent -- just keeping a list of future changes!

**Comment by martinpeck** [comment]
@rik-cross can we close this?

**Comment by rik-cross** [comment]
yep, closing...
