### ISSUE TITLE
Automatic generation of PDFs

### ISSUE THREAD

**Issue by gahjelle** [CodeClub/lesson_format#17]
Hi,

I noticed that autogeneration of PDFs had been disabled. Together with the team here in Norway I have implemented a simple solution that uses phantomjs to convert the pandoc created HTML to PDF. With the potential exception of details like page breaking this seems to give very nice results with the added bonus of the PDFs visually staying very (too?) close to the HTML.

Currently we have the update in my fork at https://github.com/gahjelle/lesson_format. However, unless this goes against any of your future plans for PDFs, I would love to send a pull request your way?

**Comment by shaidams64** [comment]
@andylolz hi Andy, I know this issue is closed but i'll be very grateful if you can guide me how to insert proper page breaks in pdfs created by phantomjs. I saw you are suggesting adding manual page-breaks, could you pleas elaborate what you mean by that? thanks a lot!

**Comment by andylolz** [comment]
Hi @shaidams64. My memory of this is hazy, but it’s all explained above. It looks like I couldn’t get `page-break-inside` to work, but `page-break-before` worked _some of the time_ (i.e. for some elements but not others).

It looks like you’re using phantomjs 2.0 – it’s a shame to hear the problem still isn’t resolved. I don’t think I ever really satisfactorily solved the problem, but I’d hoped upgrading to 2.0 would do the trick.
