### ISSUE TITLE
Languages on CCW project site in alphabetical order

### ISSUE THREAD

**Issue by freyjaodds** [CodeClub/lesson_format#170]
The order of the language list on http://projects.codeclubworld.org/ has changed, is it possible to make it alphabetical?

**Comment by martinpeck** [comment]
Yes (it's possible), but No (it's not likely to happen). We're not actively maintaining this code, and I believe that alphabetical ordering would cause other problems.

**Comment by andylolz** [comment]
They’re currently [sorted by project count](https://github.com/CodeClub/lesson_format/blob/814c4821/build.py#L999)! (I wondered why they occasionally move about!)

**Comment by martinpeck** [comment]
@rik-cross are you ok with us closing this?

**Comment by rik-cross** [comment]
yep i'll close this.
