### ISSUE TITLE
Remove survey from 'new' project text

### ISSUE THREAD

**Issue by CodeClubRik** [CodeClub/lesson_format#171]
If a project is marked as `beta: true`, this header is displayed:

![screen shot 2015-09-04 at 19 14 36](https://cloud.githubusercontent.com/assets/7372432/9691253/3ad298f0-5339-11e5-8fbe-998f44154a3b.png)

Please can we remove the link to the surveys, as now for the uk site we have a feedback button at the bottom of each project.

**Comment by CodeClubRik** [comment]
The example above is from a Danish project -- I suggest we also remove the `beta: true` property from all translations, unless we can localise the text and make it relevant to translations.

**Comment by martinpeck** [comment]
Isn't removing `beta: true` a fix for this issue in general?

**Comment by CodeClubRik** [comment]
For translations, I think it is.
For English projects, it depends -- should these be updated and kept in line with those on the new site? Or is it frozen in it's current state?

**Comment by martinpeck** [comment]
bcf49f423f022ac684cf7eede42e98f0f20dda34 disables the beta feature entirely
