### ISSUE TITLE
Styling of Trinkets

### ISSUE THREAD

**Issue by rikcross** [CodeClub/lesson_format#184]
Now that the HTML projects have been updated to use Trinket, there are a couple of styling issues that need fixing.

![screen shot 2016-02-21 at 20 29 08](https://cloud.githubusercontent.com/assets/7372432/13205207/a73846b2-d8da-11e5-90ac-5b85c98b1696.png)

1) The HTML for displaying a Trinket is:

```
<div class="trinket">
  <iframe src="https://trinket.io/embed/html/a41e4e1c5c?outputOnly=true&start=result" width="600" height="500" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen>
  </iframe>
  <img src="magazine-final.png">
</div>
```

It would be great if the trinket (and not the image) was displayed on the website, and vice-versa for the pdf. I guess this is similar to the styling for the Scratch iframes.

2) The Trinkets should be center-aligned.

Cheers.

**Comment by martinpeck** [comment]
I've only been and gone and done it!

**Comment by rikcross** [comment]
:+1:
