### ISSUE TITLE
Projects email

### ISSUE THREAD

**Issue by Jxr227** [CodeClub/lesson_format#187]
@martinpeck 
I tried to email the address you provided (projects@codeclub.org.uk)
and it complains, is it projects@codeclub.org?

**Comment by martinpeck** [comment]
Nope. That address is correct. I've just mailed it myself (from various e-mail addresses), and it works for me.

If you let me know what error you're getting in the bounced e-mail I might be able to help, but projects@codeclub.org.uk is working for us.

**Comment by Jxr227** [comment]
My mistake, I was being an idiot.

**Comment by martinpeck** [comment]
:)

**Comment by andylolz** [comment]
@martinpeck Hi, I intended to remove my email address from #168 once James replied / emailed, but I no longer have permission to do that. Would you mind doing that? Thanks.

**Comment by martinpeck** [comment]
@andylolz done!

**Comment by andylolz** [comment]
Great – thanks!
