### ISSUE TITLE
HTML & CSS Term 1 not showing

### ISSUE THREAD

**Issue by rik-cross** [CodeClub/lesson_format#195]
Term 1 of HTML & CSS is not showing:

![screen shot 2016-09-02 at 13 01 55](https://cloud.githubusercontent.com/assets/18461167/18203232/7ff87cf4-710d-11e6-9ffb-e8ca015c142c.png)

I think this is because the codeclubrobot is having trouble with the 'Recipe' project. Until recently, the project had it's files split over `recipe` and `Recipe` folders. @grega helped fix this, and I know that I had to stop ignoring case sensitivity on my local machine.

Does something similar need doing for the environment in which codeclubrobot auto-builds?

**Comment by phazor** [comment]
Is there an alternate location to source the HTML & CSS 1 projects from in the meantime?

**Comment by martinpeck** [comment]
Is this not simply that the files you're trying to build don't exist?

I see this in the logs...

```
Traceback (most recent call last):
  File "/app/build.py", line 890, in build
    term = parse_manifest(m, theme)
  File "/app/build.py", line 1015, in parse_manifest
    project = parse_project_manifest(p, base_dir, theme)
  File "/app/build.py", line 1036, in parse_project_manifest
    filename  = expand_glob(base_dir, p['filename'],     one_file = True)
  File "/app/build.py", line 1271, in expand_glob
    raise AssertionError("Looked for one file matching '%s', found: %r"%(os.path.join(base_dir,paths), output))
AssertionError: Looked for one file matching '/app/lessons/webdev/zh-CN/Recipe/Recipe.md', found: []
Traceback (most recent call last):
  File "/app/build.py", line 890, in build
    term = parse_manifest(m, theme)
  File "/app/build.py", line 1015, in parse_manifest
    project = parse_project_manifest(p, base_dir, theme)
  File "/app/build.py", line 1036, in parse_project_manifest
    filename  = expand_glob(base_dir, p['filename'],     one_file = True)
  File "/app/build.py", line 1271, in expand_glob
    raise AssertionError("Looked for one file matching '%s', found: %r"%(os.path.join(base_dir,paths), output))
AssertionError: Looked for one file matching '/app/lessons/webdev/en-GB/Recipe/Recipe.md', found: []
```

Note that in both cases the .md file has an upper case `R` for `Recipe.md`, where as the materials in the webdev-curriculum repo do not...

https://github.com/CodeClub/webdev-curriculum/blob/master/en-GB/Recipe/recipe.md
https://github.com/CodeClub/webdev-curriculum/tree/master/zh-CN/Recipe/recipe.md

My guess is that fixing the `.manifest` files to refer to existing files will fix this.

**Comment by martinpeck** [comment]
I've made the manifest changes in https://github.com/CodeClub/webdev-curriculum/commit/81c935944e5eb4d9d40d7c1e0a2c9e265357014a

**Comment by rik-cross** [comment]
Whoops - thanks @martinpeck!

**Comment by martinpeck** [comment]
I'm running a build with the changes to confirm this.

**Comment by rik-cross** [comment]
@martinpeck - I've tested it, and you were right. The changes are now live :)

**Comment by rik-cross** [comment]
Hi @phazor - sorry that the projects were unavailable, but everything should be fixed now.

**Comment by martinpeck** [comment]
See! I'm not just a pretty face! :)
